export const REGISTER_ACCOUNT_REQUEST = "registerAccount/REGISTER_ACCOUNT_REQUEST";
export const REGISTER_ACCOUNT_SUCCESS = "registerAccount/REGISTER_ACCOUNT_SUCCESS";
export const REGISTER_ACCOUNT_FAIL = "registerAccount/REGISTER_ACCOUNT_FAIL";
